version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "22:00" # 10pm UTC
    groups:
      all-minor-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
