---
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # The Kafka Broker
  # https://kafka.apache.org/documentation/#gettingStarted
  broker:
    image: confluentinc/cp-kafka:7.6.1
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "29093:29093"
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: "localhost"
      # setup three listeners:
      # 1. INTERNAL for traffic within this Docker Compose network,
      # 2. LISTENER_HOST_MACHINE for traffic from the machine running Docker (i.e. localhost), and
      # 3. LISTENER_OTHER_DOCKER_NETWORK for traffic from another Docker container running with a separate network on the same host machine.
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,LISTENER_HOST_MACHINE:PLAINTEXT,LISTENER_OTHER_DOCKER_NETWORK:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://broker:29092,LISTENER_HOST_MACHINE://broker:9092,LISTENER_OTHER_DOCKER_NETWORK://broker:29093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,LISTENER_HOST_MACHINE://localhost:9092,LISTENER_OTHER_DOCKER_NETWORK://host.docker.internal:29093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

  # Confluent Schema Registry provides a serving layer for your metadata.
  # https://github.com/confluentinc/schema-registry
  schema-registry:
    build:
      context: .
      dockerfile: schema-registry.Dockerfile
    container_name: schema-registry
    depends_on:
      - zookeeper
      - broker
    ports:
      - "8081:8081"
      - "9500:9500"
    environment:
      SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_METHODS: "GET,POST,PUT,DELETE,OPTIONS"
      SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_ORIGIN: "*"
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "broker:29092"
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_JMX_HOSTNAME: "localhost"
      SCHEMA_REGISTRY_JMX_PORT: 9500
