name: Bug Report
description: File a bug report
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Hi there,
        Thank you for opening an issue. Please note that we try to keep the issue tracker reserved for bug reports and feature requests.
        For general usage questions, please see: https://www.terraform.io/community.html.
  - type: input
    id: terraform-version
    attributes:
      label: Terraform Provider Version
      description: Run `terraform providers` to show the version of the terraform provider. If you are not running the latest version of the terraform provider, please upgrade or check the changelogs because your issue may have already been fixed.
      placeholder: ex. v3.28.0
    validations:
      required: true
  - type: input
    id: terraform-cli
    attributes:
      label: Terraform Version
      description: Run `terraform -v` to show the version of the terraform cli.
      placeholder: ex. v1.5.3
    validations:
      required: true
  - type: textarea
    id: affected-resources
    attributes:
      label: What resources or data sources are affected?
      description: |
        Please list the resources as a list, for example:
          - opc_instance
          - opc_storage_volume
        If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.
      placeholder: ex. schemaregistry_schema
    validations:
      required: true
  - type: textarea
    id: terraform-config
    attributes:
      label: Terraform Configuration Files
      description: Copy-paste your Terraform configurations here - for large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
      render: hcl
  - type: textarea
    id: debug-output
    attributes:
      label: Relevant debug or panic output
      description: |
        Provide a link to a GitHub Gist containing the complete debug or panic output: https://www.terraform.io/docs/internals/debugging.html.
        Please do NOT paste the output in the issue; only paste a link to the Gist.
        **NOTE:** Remember to review debug output before posting, and _redact any sensitive data_.
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What should have happened?
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: |
        Please list the steps required to reproduce the issue, for example:
        1. `terraform apply`
  - type: textarea
    id: misc-notes
    attributes:
      label: Important Facts
      description: |
        Is there anything atypical about your configuration that we should know?
  - type: textarea
    id: references
    attributes:
      label: References
      description: |
        Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here?
      placeholder: GH-0000
