# Terraform Provider release workflow.
name: Release
run-name: Release ${{ github.sha }} by @${{ github.actor }}

on:
  push:
    branches:
      - main
    paths:
      - "**/**.go"
      - "go.mod"
      - "go.sum"

permissions:
  contents: read

jobs:
  release:
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          # Allow goreleaser to access older tag information.
          fetch-depth: 0
      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version-file: "go.mod"
          cache: true
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@01dd5d3ca463c7f10f7f4f7b4f177225ac661ee4 # v6.1.0
        id: import_gpg
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
      - name: Run go-semantic-release
        uses: go-semantic-release/action@079e195a22e6f55af6c17945090eb6cce603f9a5 # v2.30.0
        with:
          hooks: goreleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}

  changelog:
    needs: release
    name: Generate Changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: go-semantic-release/action@079e195a22e6f55af6c17945090eb6cce603f9a5 # v2.30.0
        with:
          changelog-file: CHANGELOG.md
          changelog-generator-opt: "emojis=true"
          dry: true # do not create a release
          prepend: true # prepend new changelog to the existing one
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          git config --local user.name 'semantic-release[bot]'
          git config --local user.email 'semantic-release[bot]@users.noreply.github.com'
          git add CHANGELOG.md
          git commit -m "chore(release): update changelog after ${{ github.ref_name }}"
          git push origin HEAD:main
